image: php:8.0-fpm

pipelines:
   branches:
      '{master,develop}':
      - step:
          name: Build and Test
          caches:
               - composer
          script:
             - echo '******* start packages and dependencies installation *******'
             #Install and update packages
             - apt-get update
             - apt-get install git curl zip
            
             #Install xdebug for codecoverage
             - pecl install xdebug
             - docker-php-ext-enable xdebug
             - echo "xdebug.mode=coverage" > /usr/local/etc/php/php.ini
            
             #Install composer

             - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
             - composer install

             - echo '******* Run Test Suite *******'

             #Run Test Suite
             - ./vendor/bin/phpunit --coverage-text --colors=always --verbose --log-junit ./test-reports/phpunit.junit.xml --coverage-clover ./test-reports/phpunit.coverage.xml

      - step:
          name: Quality check 
          script:
             - echo '******* Quality check with sonar cloud  *******'
      - step:
          name: deploy
          script:
             - echo '******* deploy on preprod  *******'