image: php:8.0-fpm

pipelines:
   branches:
      '{master,develop}':
      - step:
          name: Build and Test
          caches:
               - composer
          script:
             - echo '******* start packages and dependencies installation *******'
             #Install and update packages
             - apt-get update
             - apt-get install -qy git curl zip
            
             #Install xdebug for codecoverage

             - pecl install xdebug
             - docker-php-ext-enable xdebug
             - echo "xdebug.mode=coverage" > /usr/local/etc/php/php.ini
            
             #Install composer

             - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
             - composer install

             - echo '******* Run Test Suite *******'

             #Run Test Suite
             - ./vendor/bin/phpunit --coverage-text --colors=always --verbose --log-junit ./test-reports/phpunit.junit.xml --coverage-clover ./test-reports/phpunit.coverage.xml

      - step:
          name: Static Code Analysis 
          script:
             - echo '******* Quality check with sonar cloud  *******'
             #Define token and others viraibles in your repository variables
             - #pipe: sonarsource/sonarcloud-scan:1.2.1
             - #pipe: sonarsource/sonarcloud-quality-gate:0.1.4
      - step:
          name: Deploy to preprod or prod
          script:
             - echo '******* deploy on preprod or prod  *******'
             #Install and update packages
             - apt-get update
             - apt-get install -qy git curl zip
             - apt-get install -y openssh-client
             #go to ssh_script.sh to define your deployement scripts
             - #ssh $USER__NAME@$SITE_DOMAIN 'bash -s' < ssh_script.sh